[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

filterwarnings =
    ignore:The configuration option "asyncio_default_fixture_loop_scope" is unset.:pytest.PytestDeprecationWarning
    ignore:Support for class-based `config` is deprecated.*:DeprecationWarning
